export const KEMBALIKAN_TARGET_PRESETS = [
  { value: "mabes", label: "Kabag Yanduan Divpropam Polri" },
  { value: "yanduan", label: "Kasubbag Yanduan" },
  { value: "kabid", label: "Kabid Propam" },
  { value: "kasatker", label: "Kasatker" },
  { value: "operator", label: "Operator Yanduan" },
]

export const STATUS_OPTIONS = [
  { value: "DALAM PROSES LIDIK", label: "DALAM PROSES LIDIK" },
  { value: "Diterima Bag Rehabpers", label: "Diterima Bag Rehabpers" },
  { value: "Gelar Lidik", label: "Gelar Lidik" },
  { value: "Gelar Perkara", label: "Gelar Perkara" },
  { value: "Hasil Sidang Disiplin", label: "Hasil Sidang Disiplin" },
  { value: "Hasil Sidang KKEP", label: "Hasil Sidang KKEP" },
  { value: "HENTI LIDIK", label: "HENTI LIDIK" },
  { value: "KATIM A SUBBID WABPROF POLDA KEP. BABEL", label: "KATIM A SUBBID WABPROF" },
  { value: "Laporan Dikirim ke Polda", label: "Laporan Dikirim ke Polda" },
  { value: "Laporan Dikirim ke Polres", label: "Laporan Dikirim ke Polres" },
  { value: "Laporan Dikirim ke Satker", label: "Laporan Dikirim ke Satker" },
  { value: "Laporan Diterima", label: "Laporan Diterima" },
  { value: "Laporan diterima Bagyanduan & Di Review Kasubag Trimlap", label: "Diterima Bagyanduan & Review Trimlap" },
  { value: "Laporan Diterima KASIPROPAM", label: "Laporan Diterima KASIPROPAM" },
  { value: "Laporan Diterima Kasubbid Paminal", label: "Laporan Diterima Kasubbid Paminal" },
  { value: "LAPORAN DITERIMA OLEH UNIT MENANGANI DAN SEDANG DALAM PENYELIDIKAN (RIKSA)", label: "Diterima Unit (Penyelidikan/Riksa)" },
  { value: "Laporan Diterima PAMINAL", label: "Laporan Diterima PAMINAL" },
  { value: "Laporan Diterima Polda", label: "Laporan Diterima Polda" },
  { value: "Laporan Diterima POLDA JABAR BAGWASSIDIK DITRESKRIMUM", label: "Diterima Bagwassidik Ditreskrim" },
  { value: "Laporan Diterima SUBBID POLDA", label: "Laporan Diterima Subbid Polda" },
  { value: "Laporan Diverifikasi KABID PROPAM", label: "Diverifikasi Kabid Propam" },
  { value: "Laporan Masuk", label: "Laporan Masuk" },
  { value: "Laporan Selesai", label: "Laporan Selesai" },
  { value: "Laporan Selesai (dikirim ke BAGWASSIDIK DIRESKRIMUM)", label: "Selesai (Bagwassidik Direskrimum)" },
  { value: "Laporan Selesai Restorative Justice", label: "Selesai Restorative Justice" },
  { value: "Lidik", label: "Lidik" },
  { value: "LIMPAH KE UNIT PROVOS", label: "Limpah ke Unit Provos" },
  { value: "LIMPAH SUBBIDAWBPROF", label: "Limpah Subbid Wabprof" },
  { value: "MASIH DALAM LIDIK", label: "Masih Dalam Lidik" },
  { value: "PELIMPAHAN DP3D", label: "Pelimpahan DP3D" },
  { value: "Pemberkasan", label: "Pemberkasan" },
  { value: "Perdamaian", label: "Perdamaian" },
  { value: "Proses Lidik", label: "Proses Lidik" },
  { value: "Proses Sidang KKEP", label: "Proses Sidang KKEP" },
  { value: "PUTUSAN SIDANG", label: "Putusan Sidang" },
  { value: "PUTUSAN SIDANG-", label: "Putusan Sidang" },
  { value: "Restorative Justice", label: "Restorative Justice" },
  { value: "Riksa Cepat", label: "Riksa Cepat" },
  { value: "RJ", label: "RJ" },
  { value: "SELESAI SIDANG", label: "Selesai Sidang" },
  { value: "TEGURAN TERTULIS", label: "Teguran Tertulis" },
  { value: "TERBIT DP3D", label: "Terbit DP3D" },
  { value: "TERBIT LP", label: "Terbit LP" },
  { value: "TIDAK TERBUKTI", label: "Tidak Terbukti" },
  { value: "Verifikasi Kabag Yanduan", label: "Verifikasi Kabag Yanduan" },
  { value: "Verifikasi Laporan", label: "Verifikasi Laporan" },
]
